### ISSUE TITLE
Uncaught TypeError: g is not a function

### ISSUE THREAD

**Issue by joncon62** [Draggable/formeo#396]
When I try using the latest release I get the following console error
```
formeo.min.js:8 Uncaught TypeError: g is not a function
    at formeo.min.js:8:8642
    at formeo.min.js:8:140
    at formeo.min.js:8:207
(anonymous)	@	formeo.min.js:8
(anonymous)	@	formeo.min.js:8
(anonymous)	@	formeo.min.js:8
```
I'm calling formeo with
`<script src="https://draggable.github.io/formeo/assets/js/formeo.min.js"></script>`

This also fails
`<script type="text/javascript" src="https://unpkg.com/formeo@3.1.3/dist/formeo.min.js"></script>`

If I use a downlevel version it works fine
`<script type="text/javascript" src="https://unpkg.com/formeo@3.1.2/dist/formeo.min.js"></script>`

so there is something not working with 3.1.3

**Comment by kevinchappell** [comment]
Thanks for reporting. I will look into what changed

**Comment by leandroneves-net** [comment]
Hello, 

Same problem. I'm reverting to 3.1.2 with sucess.
